// List of Indian languages and common international languages
const LANGUAGE_OPTIONS_RAW = [
  'English',
  'Hindi',
  'Tamil',
  'Telugu',
  'Kannada',
  'Malayalam',
  'Marathi',
  'Gujarati',
  'Bengali',
  'Punjabi',
  'Urdu',
  'Odia',
  'Assamese',
  'Maithili',
  'Sanskrit',
  'Santali',
  'Kashmiri',
  'Nepali',
  'Konkani',
  'Manipuri',
  'Sindhi',
  'Dogri',
  'Bodo',
  'Khasi',
  'Garo',
  'Tuluva',
  'Kodava',
  'Kuvi',
  'Gondi',
  'Ho',
  'Mundari',
  'Santhali',
  'Ao',
  'Angami',
  'Konyak',
  'Chang',
  'Lotha',
  'Phom',
  'Sangtam',
  'Sumi',
  'Yimchungru',
  'Zeliang',
  'Liangmai',
  'Mao',
  'Chokri',
  'Karbi',
  'Dimasa',
  'Deori',
  'Rabha',
  'Hajong',
  'Mishing',
  'Kachari',
  'Chutiya',
  'Sonowal',
  'Mech',
  'Tripuri',
  'Reang',
  'Jamatia',
  'Chakma',
  'Marma',
  'Mru',
  'Khumi',
  'Kuki',
  'Tangkhul',
  'Thadou',
  'Vaiphei',
  'Zou',
  'Zeme',
  'Kabui',
  'Karbi',
  'Garo',
  'Khasi',
  'Jaintia',
  'War',
  'Khun',
  'Pnar',
  'Maram',
  'Paite',
  'Ralte',
  'Hrangkhol',
  'Mizo',
  'Chakma',
  'Marma',
  'Arakanese',
  'Bangla',
  'Balti',
  'Ladakhi',
  'Sukumbasi',
  'Monpa',
  'Lepcha',
  'Limbu',
  'Rai',
  'Newari',
  'Maithili',
  'Magahi',
  'Angika',
  'Bajjika',
  'Bhojpuri',
  'Chhattisgarhi',
  'Bundeli',
  'Awadhi',
  'Bagheli',
  'Mal Pahari',
  'Ho',
  'Mundari',
  'Santhali',
  'Khond',
  'Gondi',
  'Kui',
  'Kuvi',
  'Chhattisgarhi',
  'Harauti',
  'Dhundari',
  'Shekhawati',
  'Mewari',
  'Marwari',
  'Wagdi',
];

// Ensure options are unique to avoid React duplicate key warnings.
export const LOCAL_LANGUAGE_OPTIONS = Array.from(new Set(LANGUAGE_OPTIONS_RAW));

// Top foreign languages commonly selected by doctors for international patients.
export const FOREIGN_LANGUAGE_OPTIONS = [
  'English',
  'French',
  'German',
  'Spanish',
  'Arabic',
  'Mandarin Chinese',
  'Japanese',
  'Korean',
  'Russian',
  'Portuguese',
];

// Backward compatibility for existing imports.
export const LANGUAGE_OPTIONS = LOCAL_LANGUAGE_OPTIONS;

// List of all Indian states and Union Territories
export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Lakshadweep',
  'Delhi',
  'Puducherry',
  'Ladakh',
];
